# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

actions_path 'actions'

platform :android do

  desc "Runs all the tests"
  lane :test do
    gradle(task: "check")
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    increment_android_version_code(path: "app/version.properties")
    # gradle(task: "clean assembleFlowRelease")
    # crashlytics(
    #       groups: "testers",
    #       notifications: true,
    #     )
    git_commit(path: "app/version.properties", message: "Version Bump to #{lane_context[SharedValues::ANDROID_VERSION_CODE]} [ci skip]")
    push_to_git_remote(
          local_branch: git_branch,
          force: false,
          tags: false
        )
    #slack(
    #        message: "Successfully distributed a new beta build: #{lane_context[SharedValues::ANDROID_VERSION_CODE]}"
    #     )
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end

  error do |lane, exception|
          slack(
            message: exception.message,
            success: false
          )
  end
end
