-keep @org.junit.runner.RunWith public class *
-keep class android.support.test.internal** { *; }
-keep class org.junit.** { *; }
-keep public class org.akvo.flow.activity.** { *; }
-keep public class org.akvo.flow.serialization.** { *; }
-keep public class org.akvo.flow.ui.** { *; }